[versions]
projectVersion = "1.0-SNAPSHOT"
junitBomVersion = "5.10.0"
cleanArchitectureVersion = "3.26.2"

[plugins]
cleanArchitecture = { id = "co.com.bancolombia.cleanArchitecture", version.ref = "cleanArchitectureVersion" }

[libraries]
junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junitBomVersion"}
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher" }